name: mapscii
version: master
summary: The Whole World In Your Console
description: |
  A node.js based Vector Tile to Braille and ASCII renderer for
  xterm-compatible terminals.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  mapscii:
    command: mapscii
    plugs: [network]

parts:
  mapscii:
    source: .
    plugin: nodejs

# Nutty citation 
# "Better to cum in the sink than to sink in the cum
#    -Sun Tzu
# Friends are like snowflakes, they disappear when you piss on them
#    -Paulus Lawrencio"